version: '3'
services:
  kaggle_container:
    container_name: 'gpu'
    hostname: 'gpu'
    shm_size: '60g' # shared memory size

    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    working_dir: /workspace
    tty: true
    volumes:
      - type: bind
        source: /mnt2tb # relative path to external ssd
        target: /external_disk_2tb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]