# refs
# - https://docs.github.com/ja/actions/learn-github-actions/understanding-github-actions
# - https://docs.github.com/ja/actions/automating-builds-and-tests/building-and-testing-python
# - https://github.com/actions/setup-python/tree/main
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
# on: [push] # push event
on:
  workflow_dispatch: # manual event

jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hello world python file
        run: echo "print('Hello world')" > hello.py
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python -v
      - run: python hello.py